name: ${project.name}
main: me.danjono.inventoryrollback.InventoryRollback
version: ${project.version}
description: ${project.description}
author: ${project.organization.name}
api-version: 1.13
commands:
  inventoryrollback:
    description: ${project.description}
    usage: /<command>
    permission: inventoryrollback.cmd
    aliases: ir
permissions:
  inventoryrollback.*:
    description: Gives access to all InventoryRollback commands.
    children:
      inventoryrollback.cmd: true
      inventoryrollback.deathsave: true
      inventoryrollback.joinsave: true
      inventoryrollback.leavesave: true
      inventoryrollback.worldchangesave: true
      inventoryrollback.enable: true
      inventoryrollback.disable: true
      inventoryrollback.reload: true      
      inventoryrollback.restore: true
      inventoryrollback.forcebackup: true
      inventoryrollback.version: true
    default: op
  inventoryrollback.cmd:
    description: Allows InventoryRollback commands to work.
    default: true
  inventoryrollback.deathsave:
    description: Player inventories will be saved when they die.
    default: true
  inventoryrollback.joinsave:
    description: Player inventories will be saved when the join.
    default: true
  inventoryrollback.leavesave:
    description: Player inventories will be saved when they leave.
    default: true
  inventoryrollback.worldchangesave:
    description: Player inventories will be saved when they change worlds.
    default: true
  inventoryrollback.enable:
    description: Grants access to enable the plugin globally.
    default: op
  inventoryrollback.disable:
    description: Grants access to disable the plugin globally. 
    default: op
  inventoryrollback.reload:
    description: Grants access to reload the plugin configuration.
    default: op
  inventoryrollback.restore:
    description: Grants access to perform player roll backs.
    default: op
  inventoryrollback.forcebackup:
    description: Forces a backup for an online player. 
    default: op
  inventoryrollback.version:
    description: Allows player to see the version the plugin is running on the server. 
    default: true