name: ${project.name}
main: ${project.groupId}.InventoryRollbackPlus
version: ${project.version}
description: ${project.description}
author: ${project.organization.name}
authors: [${project.organization.name}, danjono]
api-version: 1.13
folia-supported: true

loadbefore:
  - DeluxeCombat
  - DeadChest
  - AngelChest
  - SavageDeathChest

commands:
  inventoryrollbackplus:
    description: ${project.description}
    usage: /irp <subcommand>
    aliases: [ir, irp, inventoryrollback]

permissions:
  inventoryrollbackplus.*:
    description: Gives access to all InventoryRollbackPlus commands.
    children:
      inventoryrollbackplus.cmd: true
      inventoryrollbackplus.deathsave: true
      inventoryrollbackplus.joinsave: true
      inventoryrollbackplus.leavesave: true
      inventoryrollbackplus.worldchangesave: true
      inventoryrollbackplus.enable: true
      inventoryrollbackplus.disable: true
      inventoryrollbackplus.reload: true
      inventoryrollbackplus.restore: true
      inventoryrollbackplus.forcebackup: true
      inventoryrollbackplus.version: true
      inventoryrollbackplus.help: true
      inventoryrollbackplus.adminalerts: true
      inventoryrollbackplus.viewbackups: true
    default: op
  inventoryrollbackplus.cmd:
    description: Allows InventoryRollback commands to work.
    default: true
  inventoryrollbackplus.deathsave:
    description: Player inventories will be saved when they die.
    default: true
  inventoryrollbackplus.joinsave:
    description: Player inventories will be saved when the join.
    default: true
  inventoryrollbackplus.leavesave:
    description: Player inventories will be saved when they leave.
    default: true
  inventoryrollbackplus.worldchangesave:
    description: Player inventories will be saved when they change worlds.
    default: true
  inventoryrollbackplus.enable:
    description: Grants access to enable the plugin globally.
    default: op
  inventoryrollbackplus.disable:
    description: Grants access to disable the plugin globally.
    default: op
  inventoryrollbackplus.reload:
    description: Grants access to reload the plugin configuration.
    default: op
  inventoryrollbackplus.restore:
    description: Grants access to perform player roll backs.
    default: op
    children:
      inventoryrollbackplus.viewbackups: true
      inventoryrollbackplus.restore.teleport:
        default: op
        description: Allow the staff member to teleport to the location where the backup was saved
  inventoryrollbackplus.forcebackup:
    description: Forces a backup for an online player.
    default: op
  inventoryrollbackplus.viewbackups:
    description: Allows player to view player backups but can't take items from the backups or restore the target's inventory
    default: op
  inventoryrollbackplus.adminalerts:
    description: Allows player to receive extra notifications related to the plugin when joining.
    default: op
  inventoryrollbackplus.version:
    description: Allows player to see the version the plugin is running on the server.
    default: true
  inventoryrollbackplus.help:
    description: Get the list of commands and what they do
    default: true

  # ---- LEGACY COMPATIBILITY ----
  inventoryrollback.cmd:
    description: Allows InventoryRollback commands to work.
    default: false
    children:
      inventoryrollbackplus.cmd: true
  inventoryrollback.deathsave:
    description: Player inventories will be saved when they die.
    default: false
    children:
      inventoryrollbackplus.deathsave: true
  inventoryrollback.joinsave:
    description: Player inventories will be saved when the join.
    default: false
    children:
      inventoryrollbackplus.joinsave: true
  inventoryrollback.leavesave:
    description: Player inventories will be saved when they leave.
    default: false
    children:
      inventoryrollbackplus.leavesave: true
  inventoryrollback.worldchangesave:
    description: Player inventories will be saved when they change worlds.
    default: false
    children:
      inventoryrollbackplus.worldchangesave: true
  inventoryrollback.enable:
    description: Grants access to enable the plugin globally.
    default: false
    children:
      inventoryrollbackplus.enable: true
  inventoryrollback.disable:
    description: Grants access to disable the plugin globally.
    default: false
    children:
      inventoryrollbackplus.disable: true
  inventoryrollback.reload:
    description: Grants access to reload the plugin configuration.
    default: false
    children:
      inventoryrollbackplus.reload: true
  inventoryrollback.restore:
    description: Grants access to perform player roll backs.
    default: false
    children:
      inventoryrollbackplus.restore: true
  inventoryrollback.forcebackup:
    description: Forces a backup for an online player.
    default: false
    children:
      inventoryrollbackplus.forcebackup: true
  inventoryrollback.version:
    description: Allows player to see the version the plugin is running on the server.
    default: false
    children:
      inventoryrollbackplus.version: true